version: "3.5"

services:
  api01: &api
    build: 
      dockerfile: ./Dockerfile
    hostname: api01
    container_name: api01
    environment:
      - DB_HOSTNAME=db
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - API_USE_DB_FUNC=true
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"

  api02:
    <<: *api
    container_name: api02
    hostname: api02
    ports:
      - "3002:3000"

  lb:
    build: 
      dockerfile: ./Load.Dockerfile
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
  
  # pgadmin:
  #   image: dpage/pgadmin4:7.6
  #   tty: true
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@user.com
  #     - PGADMIN_DEFAULT_PASSWORD=123456
  #   ports:
  #     - "9000:80"
  #   depends_on:
  #     - db


networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
